### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by CrystallineButterfly** [Paul-js-hub/my-catalog#5]
In this pull request, we have

- Created an empty repository for our group project.
- Followed the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] Ruby Group Capstone Project](https://github.com/microverseinc/curriculum-ruby/projects/1) board and opened the GitHub project (Kanban board) in our team repo.
- Created tasks on our Kanban board based on the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md).
- Each task has a separate card, descriptive title, points in the [Xpt] prefix, and a description of the task.
- Each of the team members has been assigned to the cards as follows:
- 
 🟢 Group-Tasks: @Paul-js-hub @udeaghad @CrystallineButterfly 
🟢 Team-Member-1: @udeaghad 
🟢 Team-Member-2: @Paul-js-hub 
🟢 Team-Member-3: @CrystallineButterfly 

Full Kanban Board link is https://github.com/Paul-js-hub/my-catalog/projects/1 ☑️

Kindly review and approve

**Comment by prolajumokeoni** [comment]
Hi @CrystallineButterfly, @Paul-js-hub and @udeaghad  
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Good Title 👍🏿 
- Descriptive issue 🤝 



## Required Changes ♻️
- Based on the [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/setup_kanban_board.md#project-requirements):

- [ ] Kindly break down the group task into mini tasks, and create separate cards for each mini task, remember all group task should be assigned to all group members

- [ ]  Kindly break each [Team member's](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) task into mini tasks and create separate cards for each mini task, remember that each new mini task should be assigned to the appropriate team memeber
- Please note:  `each card should have the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. You shouldn't change the points after dividing up cards, even if the actual work takes longer`

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Deepakdanger** [comment]
Hi @TEAM, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
